steps:
  # - name: "bash"
  #   args: ["mv", ".env.test", ".env"]
  - name: node:v20.18.1
    entrypoint: yarn
    args: ['install']
  - name: node:v20.18.1
    entrypoint: yarn
    args: ["run", "build"]

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./build", "gs://www.geek-gike.com"]
timeout: 900s
