steps:
  # - name: "bash"
  #   args: ["mv", ".env.test", ".env"]
  - name: "gcr.io/cloud-builders/yarn"
    args: ["install"]
  - name: "gcr.io/cloud-builders/yarn"
    args: ["run", "build"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./build", "gs://www.geek-gike.com"]
timeout: 900s
